#!/bin/zsh

# Use modern completion system
autoload -Uz compinit
compinit

# Use up arrow to search through history
autoload -U           up-line-or-beginning-search
zle      -N           up-line-or-beginning-search
bindkey  "$key[Up]"   up-line-or-beginning-search

# Likewise for down arrow
autoload -U           down-line-or-beginning-search
zle      -N           down-line-or-beginning-search
bindkey  "$key[Down]" down-line-or-beginning-search


