#!/bin/zsh

if [ "$(uname)" = "Darwin" ]
then
  # For MacOS compatibility
  export COLORTERM=1
else
  # Use directory colors
  eval "$(dircolors -b)"
fi

# Some aliases
alias ls='ls --color=auto'
alias tree='tree -C'

