#!/bin/sh

set -e

changed=

install_file ()
{
  src_file="$1"
  dest_file="${HOME}/$1"

  if ! cmp -s "$src_file" "$dest_file"
  then
    echo "Copying $src_file -> $dest_file"
    cp "$src_file" "$dest_file"
    changed=1
  fi
}

require_dir ()
{
  directory="$1"

  if [ ! -d "$directory" ]
  then
    echo "Creating directory $directory"
    mkdir -p "$directory"
    changed=1
  fi
}


# Install GHCi configuration
if [ -d "$HOME/.ghcup" ]
then
  install_file ".ghci"
else
  echo 'GHC not installed, skipping'
fi

# Install vim configuration
if [ -f "/bin/vim" ]
then
  install_file ".vimrc"
else
  echo 'Vim not installed, skipping'
fi

if [ -f "/bin/zsh" ]
then
  if [ "generators/prompt" -nt ".zshrc.d/00_prompt" ]
  then
    echo 'Prompt configuration is out of date, rebuilding'
    ./generators/prompt
  fi

  # Install zsh configuration
  require_dir "$HOME/.zshrc.d"
  install_file ".zshrc"
  install_file ".zshrc.d/00_prompt"
  install_file ".zshrc.d/01_history"
  install_file ".zshrc.d/02_completion"
  install_file ".zshrc.d/03_colors"
  install_file ".zshrc.d/04_path"
  install_file ".zshrc.d/10_ghcup"
  if [ -f "/bin/command-not-found" ]
  then
    install_file ".zshrc.d/20_command_not_found"
  else
    echo 'Command-Not-Found not installed, skipping'
  fi

  # Update shell
  if [ "$SHELL" != "/bin/zsh" ]
  then
    echo 'Setting shell to /bin/zsh'
    chsh -s /bin/zsh
  fi
else
  echo 'Zsh not installed, skipping'
fi

# Configure Git and install plugins
if [ -f "/usr/bin/git" ]
then
  # Main configuration
  install_file ".gitconfig"

  # Plugins
  require_dir "$HOME/.local/bin"
  install_file ".local/bin/git-amend"
else
  echo 'Git not installed, skipping'
fi


if [ "$changed" != 1 ]
then
  echo 'No changes made'
fi

