#!/bin/sh

set -e

changed=

has_command ()
{
  if which "$1" >/dev/null
  then
    return 0
  else
    return 1
  fi
}

install_file ()
{
  src_file="$1"
  dest_file="${HOME}/$1"

  if ! cmp -s "$src_file" "$dest_file"
  then
    echo "Copying $src_file -> $dest_file"
    cp "$src_file" "$dest_file"
    changed=1
  fi
}

require_dir ()
{
  directory="$1"

  if [ ! -d "$directory" ]
  then
    echo "Creating directory $directory"
    mkdir -p "$directory"
    changed=1
  fi
}


# Install vim configuration
if has_command "vim"
then
  require_dir "$HOME/.vim"
  require_dir "$HOME/.vim/autoload"

  if [ ! -f "$HOME/.vim/autoload/plug.vim" ]
  then
    echo 'Downloading Vim-Plug'
    curl -sS -o "$HOME/.vim/autoload/plug.vim" \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  install_file ".vimrc"

  require_dir "$HOME/.vim/after"

  require_dir "$HOME/.vim/after/ftplugin"
  install_file ".vim/after/ftplugin/c.vim"
  

  require_dir "$HOME/.vim/plugin"
  install_file ".vim/plugin/catppuccin.vim"
  install_file ".vim/plugin/lightline.vim"
else
  echo 'Vim not installed, skipping'
fi

if has_command "zsh"
then
  if [ "generators/prompt" -nt ".zshrc.d/00_prompt" ]
  then
    echo 'Prompt configuration is out of date, rebuilding'
    ./generators/prompt
  fi

  # Install zsh configuration
  require_dir "$HOME/.zshrc.d"
  install_file ".zshrc"
  install_file ".zshrc.d/00_prompt"
  install_file ".zshrc.d/01_history"
  install_file ".zshrc.d/02_completion"
  install_file ".zshrc.d/03_colors"
  install_file ".zshrc.d/04_path"
  install_file ".zshrc.d/10_ghcup"
  if [ -f "/bin/command-not-found" ]
  then
    install_file ".zshrc.d/20_command_not_found"
  else
    echo 'Command-Not-Found not installed, skipping'
  fi

  # Update shell
  if [ "$SHELL" != "/bin/zsh" ]
  then
    echo 'Setting shell to /bin/zsh'
    chsh -s /bin/zsh
  fi
else
  echo 'Zsh not installed, skipping'
fi

# Configure Git and install plugins
if has_command "git"
then
  # Main configuration
  install_file ".gitconfig"

  # Plugins
  require_dir "$HOME/.local/bin"
  install_file ".local/bin/git-amend"
  install_file ".local/bin/git-statusbar"
else
  echo 'Git not installed, skipping'
fi

# Install GHCi configuration
if has_command "ghci"
then
  install_file ".ghci"
else
  echo 'GHC not installed, skipping'
fi


if [ "$changed" != 1 ]
then
  echo 'No changes made'
fi

